-- Migration: Create PHALGA database tables in Supabase (PostgreSQL)
-- Converted from MySQL schema to PostgreSQL syntax

-- Create LGUS table
CREATE TABLE IF NOT EXISTS "LGUS" (
  "PSGC" VARCHAR(12) NOT NULL PRIMARY KEY,
  "GEOLEVEL" VARCHAR(10),
  "LGUNAME" VARCHAR(80)
);

-- Create REGH table (Registration Header)
CREATE TABLE IF NOT EXISTS "REGH" (
  "REGNUM" INTEGER NOT NULL UNIQUE,
  "TRANSID" CHAR(6) NOT NULL,
  "CONFCODE" VARCHAR(15),
  "PROVINCE" VARCHAR(80),
  "LGU" VARCHAR(80),
  "CONTACTPERSON" VARCHAR(80),
  "CONTACTNUM" VARCHAR(25),
  "EMAIL" VARCHAR(100),
  "REGDATE" DATE,
  PRIMARY KEY ("REGNUM", "TRANSID")
);

-- Create regd table (Registration Details)
CREATE TABLE IF NOT EXISTS "regd" (
  "CONFCODE" VARCHAR(18) NOT NULL,
  "REGNUM" INTEGER NOT NULL,
  "LINENUM" INTEGER NOT NULL,
  "NAME" VARCHAR(100),
  "ORNUM" VARCHAR(15),
  "LGU" VARCHAR(100),
  "PROVINCE" VARCHAR(60),
  "BARCODE" VARCHAR(30),
  "CREATELOG" VARCHAR(100),
  "RELEASELOG" VARCHAR(100),
  "CERTPRINTED" VARCHAR(1),
  "SESSIONCOUNT" INTEGER,
  "KITRELEASED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "DESIGNATION" VARCHAR(50),
  "PHALGAID" VARCHAR(18),
  "BRGY" VARCHAR(60),
  "PRCNUM" VARCHAR(20),
  "phalgaMEMBER" VARCHAR(10),
  "TSHIRTSIZE" VARCHAR(15),
  "LASTNAME" VARCHAR(70),
  "FIRSTNAME" VARCHAR(70),
  "MIDDLEINIT" VARCHAR(10),
  "SUFFIX" VARCHAR(12),
  "DEPOSITSLIPREFERENCE" VARCHAR(30),
  "BRANCHCODE" VARCHAR(25),
  "DEPOSITSLIPTIME" VARCHAR(30),
  "DEPOSITAMOUNT" DECIMAL(18,2),
  "EMAIL" VARCHAR(100),
  "EXPIRYDATE" DATE,
  "CONTACTNUM" VARCHAR(25),
  "COMPUTER" VARCHAR(50),
  "BANKNUM" INTEGER,
  "DATEOFBIRTH" DATE,
  "ADDRESS" VARCHAR(80),
  PRIMARY KEY ("CONFCODE", "REGNUM", "LINENUM"),
  FOREIGN KEY ("REGNUM") REFERENCES "REGH"("REGNUM") ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_lgus_lguname ON "LGUS"("LGUNAME");
CREATE INDEX IF NOT EXISTS idx_lgus_geolevel ON "LGUS"("GEOLEVEL");
CREATE INDEX IF NOT EXISTS idx_regh_confcode ON "REGH"("CONFCODE");
CREATE INDEX IF NOT EXISTS idx_regh_transid ON "REGH"("TRANSID");
CREATE INDEX IF NOT EXISTS idx_regd_regnum ON "regd"("REGNUM");
CREATE INDEX IF NOT EXISTS idx_regd_province ON "regd"("PROVINCE");

-- Enable Row Level Security (optional - can be configured later)
ALTER TABLE "LGUS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "REGH" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "regd" ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read access (adjust as needed)
CREATE POLICY "Allow public read access on LGUS" ON "LGUS"
  FOR SELECT USING (true);

CREATE POLICY "Allow public read access on REGH" ON "REGH"
  FOR SELECT USING (true);

CREATE POLICY "Allow public read access on regd" ON "regd"
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert on REGH" ON "REGH"
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public insert on regd" ON "regd"
  FOR INSERT WITH CHECK (true);
